name: Tests & Linting

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pull-requests: write
  checks: write
  statuses: write

jobs:
  test:
    name: Tests & Linting
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '18.20.4'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.0
          run_install: false
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4.2.2
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: |
          pnpm --version
          pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Run type check
        run: pnpm type-check

      - name: Run lint
        run: pnpm lint
