name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'
      - '.husky/**'
      - '.vscode/**'
      - 'README.md'
      - '.gitignore'
      - '.eslintrc'
      - '.prettierrc'
      - 'LICENSE'

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write
  deployments: write
  statuses: write

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: "18.20.4"

      - name: Install pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v4.0.0
        with:
          version: 9.15.0
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@7921ae235bdcb376cc8f22558dc5f8ddc3c3c2f9 # v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}-20241221
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm --version
          pnpm install --no-frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Run type check
        run: pnpm type-check

      - name: Run lint
        run: pnpm lint

  Check-Deploy-Needed:
    needs: Test
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check.outputs.should_deploy }}
    steps:
      - id: check
        run: |
          # Skip deployment for Dependabot PRs
          if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          # Skip if PR has skip-preview label
          elif [[ "${{ contains(github.event.pull_request.labels.*.name, 'skip-preview') }}" == "true" ]]; then
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          else
            echo "should_deploy=true" >> $GITHUB_OUTPUT
          fi

  Deploy-Preview:
    needs: [Test, Check-Deploy-Needed]
    if: needs.Check-Deploy-Needed.outputs.should_deploy == 'true'
    runs-on: ubuntu-latest
    environment:
      name: Preview
      url: ${{ steps.deploy.outputs.preview-url }}
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: "18.20.4"

      - name: Install pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v4.0.0
        with:
          version: 9.15.0
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@7921ae235bdcb376cc8f22558dc5f8ddc3c3c2f9 # v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}-20241221
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm --version
          pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Deploy to Vercel
        id: deploy
        uses: amondnet/vercel-action@7fca7241777c9bd68c0d0b06702cfb8c5e4e9c9f # v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          alias-domains: |
            pr-${{ github.event.number }}.justany.cg

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@1d90af962c5cbaaa0a2f93ae86e5a265eaa826da # v2.4.1
        with:
          message: |
            🚀 Preview déployé avec succès !

            - 🔗 URL: ${{ steps.deploy.outputs.preview-url }}
            - 📝 Commit: ${{ github.sha }}

            Pour tester :
            1. Vérifiez que le déploiement est bien terminé
            2. Testez les fonctionnalités sur l'environnement de preview
            3. Validez le bon fonctionnement de l'application
